Algoritmo "Antecessor"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   : Pega um valor digitado pelo usuário e imprime seu antecessor
// Autor(a)    : Vinícius Batista
// Data atual  : 31/08/2022
Var
valor: inteiro
antecessor: inteiro


Inicio
Escreval("Digite um número: ")
Leia(valor)
antecessor <- valor-1
Escreval("O antecessor do número digitado é: ", antecessor)


Fimalgoritmo