Algoritmo "AreaLosango"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   : Armazena as dimensões de um losango e calcula a área
// Autor(a)    : Vinícius Batista
// Data atual  : 06/09/2022
Var
d1: inteiro
d2: inteiro
area: real


Inicio
Escreval("Digite o valor do diagonal maior do losango: ")
Leia(d1)
Escreval("Digite o valor do diagonal menor do losango: ")
Leia(d2)
area <- (d1*d2)/2
Escreval("A área do quadrado é: ", area)


Fimalgoritmo