Algoritmo "AreaTriangulo"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   : Armazena as dimensões de um triangulo e calcula a área
// Autor(a)    : Vinícius Batista
// Data atual  : 31/08/2022
Var
base: real
altura: real
area: real


Inicio
Escreval("Digite a base do triangulo: ")
Leia(base)
Escreval("Digite a altura do triangulo: ")
Leia(altura)
area <- base * altura/2
Escreval("A área do triangulo: ", area)


Fimalgoritmo