Algoritmo "AreaRetangulo"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   : Armazena as dimensões de um retângulo e calcula a área
// Autor(a)    : Vinícius Batista
// Data atual  : 31/08/2022
Var
base: real
altura: real
area: real


Inicio
Escreval("Digite a base do retângulo: ")
Leia(base)
Escreval("Digite a altura do retângulo: ")
Leia(altura)
area <- base * altura
Escreval("A área do retângulo: ", area)


Fimalgoritmo