Algoritmo "SomaDosValoresEmQuadrados"
// Disciplina   : [Lógica de Programação Javascript]
// Professor   : Jailson
// Descrição   : Solicita três valores, soma e exibe o resultado em quadrados.
// Autor(a)    : Vinícius Batista
// Data atual  : 10/09/2022
Var
// Seção de Declarações das variáveis
A,B,C, resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite a o valor A:")
Leia(A)
Escreval("Digite a o valor B:")
Leia(B)
Escreval("Digite a o valor C:")
Leia(C)
resultado<-A+B+C
Escreval("A soma dos valores digitados é: ",resultado)
resultado<-resultado*resultado
Escreval("O quadrado desse valor resulta em: ",resultado)

Fimalgoritmo