Algoritmo "Sucessor"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   : Pega um valor digitado pelo usuário e imprime seu sucessor
// Autor(a)    : Vinícius Batista
// Data atual  : 05/09/2022
Var
valor: inteiro
sucessor: inteiro


Inicio
Escreval("Digite um número: ")
Leia(valor)
sucessor <- valor+1
Escreval("O sucessor do número digitado é: ", sucessor)


Fimalgoritmo